### ISSUE TITLE
Streamline Iconography to FontAwesome

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1033]
Currently there are Glyphicons being used as it is integrated with bootstrap already. Where possible we can find a FontAwesome equivalent and substitute it so the icon used are consistent and unified.

Some Glyphicons found are trash, pencil, heart, hamburger menu, wrench, flash etc.

**Comment by toolness** [comment]
Yeah! The glyphicons are 18-100k depending on the format they're retrieved in, so cutting them out will save on page load time too.

I guess we should probably also modify our gulpfile so it doesn't copy the `fonts` directory of `bootstrap`.

**Comment by AnthonyBobsin** [comment]
I've submit a pull request that replaces all current Glyphicons used with an identical FontAwesome icon. @toolness originally I took the fonts directory out of the gulpfile, but the spider.js test file was complaining because they are referenced in the bootstrap file quit a lot, so I ended up leaving it there. Let me know if I should do otherwise.
