### ISSUE TITLE
Wireframes for Club Reports

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1182]
Should include:
 * entry form 
 * viewer
 * for both mobile and desktop

Fields:
* report name
* date
* location
* # of attendees
* Narrative
* Links (as many as they want)
* What curriculum did you use? (enter urls)
* How would you rate the support you received? (1-5 + space for notes)

**Comment by hannahkane** [comment]
cc @amirad so she can follow along on this ticket

**Comment by sabrinang** [comment]
Initial wireframes on reports using content list from this issue:
![mln_directory-wireframes-group-report](https://cloud.githubusercontent.com/assets/2492510/10051703/bba58ec2-61d7-11e5-824b-3bcde447f838.png)


I haven't been able to research much of the reps reporter portal cause I don't have an account to access and but had top of a screencap for reference from the session with helen:
<img width="1280" alt="screen shot 2015-07-17 at 12 43 41 pm" src="https://cloud.githubusercontent.com/assets/2492510/10051364/f3e78d3c-61d5-11e5-9b36-e92f2a4974eb.png">
Do we want to use some of the language rep reporter uses? (i.e. "description of event" instead of "narrative")

I feel like there is more content to consider and can we get suggestions from CC/RC to see what is useful to be collected or develop the report structure together? Is there use cases where RC want to collect info on the report but not necessarily have it shown publicly on the report itself?

I think we can look into the content more and could continue to work on the UI from there

**Comment by hannahkane** [comment]
Could definitely use some feedback from @amirad @chrislarry33 and @soapdog on this one, in addition to seeking out input from RCs and CCs.

**Comment by hannahkane** [comment]
Closing because we've advanced a lot of this work. Let's open new tickets as we see the findings from the research project.
