### ISSUE TITLE
Remove /> from void elements in <head>

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1277]
... because they shouldn't have it

Let's open [another ticket](https://github.com/mozilla/teach.mozilla.org/issues/1278) for void elements in `<body>` as I anticipate the work can cause many merge conflicts.

**Comment by emmairwin** [comment]
@mmmavis can you explain a bit more about this for our Grace Hopper participants?  It sounds easy, but not 100% sure what needs removed.  (how to look for it basically)

**Comment by Pomax** [comment]
"normal" HTML elements use a syntax like `<element>some content</element>`, but there are also "void" elements that don't get content. The best example is the `<img>` tag: in old (like, 1998 old) versions of HTML, you would write this:
```
<img src="..."></img>
```
or
```
<img src="..." />
```
However, with HTML5 that changed: void elements are no longer required (in fact, are discouraged) to have that closing `/`, since HTML parsers known which elements won't ever have content. In modern HTML, you just write:
```
...stuff...
<img src="...>
...more stuff...
```

However, old habits die hard, so there's a lot of HTML code that shouldn't need that `/` at the end of tags, but still does. Prime candidates for this are `<link>`, `<meta>`, `<img>`, `<br>` and `<hr>` elements, although the full list is a little longer:
```
area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr
```
(we don't use area, base, col, command, embed, keygen, param, source, track, or wbr as far as I know, but it's worth doing a quick find-in-all-files for them!)

**Comment by Pomax** [comment]
It looks like we don't have any plain HTML, only JSX for React to autogenerate the html with, so this might not actually be applicable here.

**Comment by yunduz** [comment]
@mmmavis it seems like all html files are generated by React. Could you confirm that this issue is still applicable to this repo and if it is, could you add a bit of info about it (where to look)?

**Comment by mmmavis** [comment]
oops, my bad! I was referring to [`index-static.jsx`](https://github.com/mozilla/teach.mozilla.org/blob/develop/lib/index-static.jsx) when I first created this ticket... and for some reason I thought it was a "html" file instead of `.jsx` :stuck_out_tongue: 

I'll close this ticket as well as https://github.com/mozilla/teach.mozilla.org/issues/1278.  Sorry for the confusion!
