### ISSUE TITLE
fonts on goggles landing page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1346]
Follow up on implement the goggles landing page #1321 

Just noticed the Sign In text is in open sans when it should be Fira. 

I know you played around with this yesterday but I'm wondering if the fonts, particularly the button text, can be a little smaller to align more with Thimble?

**Comment by Pomax** [comment]
It can be as big or small as we need it to: how much smaller should it be?

**Comment by kristinashu** [comment]
'Drag and drop' button and 'Sample activity page' should be 15px. The three bottom 'Button CTA' are good. 

I think the reason Thimble fonts look thinner is because it's using 'Fira Regular' while we're use 'Fira Sans'. Not sure what the difference is but Webmaker seems to use 'Fira Sans' as well so I think we're good.

**Comment by Pomax** [comment]
The difference is mostly "whatever the @font-face rule set up". Technically the font family is called Fira Sans (to set it apart from Fira Mono, by the same foundry), with the "Regular" indicating the specific weight (regular/normal map to CSS weight 400). I'll have a look at which source Thimble's using for its fonts though - for goggles I'm simply linking to the google webfont version, Thimble might be using a hosted set instead.

**Comment by Pomax** [comment]
Hmm, after trying this, it looks like 15px for the "drag and drop me" button makes the button look pretty odd, since 15px is smaller than the universal browser default font size (16px); the paragraph text above it for instance will now be large than the button's label. 

The "drag and drop" and "sample activity" buttons are currently set to 20px , with the "CTA" buttons set to 18px, so we can set the buttons in the "steps" section to also use 18px although after changing them it feels like it makes the "drag and drop" button less prominent: it's more of a visual marker than a button in the context it's getting presented in, so having it stand out a little feels like a good thing.

current (20px):

![screenshot 57](https://cloud.githubusercontent.com/assets/177243/10546884/b06637ee-73e5-11e5-9c0b-da3cbcca0fa5.png)

18px:

![screenshot 58](https://cloud.githubusercontent.com/assets/177243/10546889/b53346a4-73e5-11e5-851b-e77ed6d3db1e.png)

15px:

![screenshot 59](https://cloud.githubusercontent.com/assets/177243/10546890/b79df4fc-73e5-11e5-9eb9-861a1e201bb6.png)

**Comment by kristinashu** [comment]
@Pomax thanks for showing me all of these! Sorry, I messed up when I said 15px. Meant to say 18px. Would be great if all the buttons were all 18px. Thanks!

**Comment by Pomax** [comment]
will do, although I still like the larger font for the "not actually a button" button =D

**Comment by Pomax** [comment]
both buttons have been updated, https://x-ray-goggles-staging.herokuapp.com should reflect the new sizes (and the "Drag and drop" button's been made a little less wide to accommodate the slightly smaller text)

**Comment by kristinashu** [comment]
Awesome, thanks! Did you update sign in to Fira?

**Comment by kristinashu** [comment]
All good!
