### ISSUE TITLE
[brand] - name and brand MLN site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1384]
**Problems:** 
We are using the Mozilla workmark but our welcome message says 'The Mozilla Learning Network' and the URL is teach.mozilla.org 
This is very confusing.

**Solutions:** 
Decide what to call the site and create a workmark.

**Seen on:** 
all pages of [MLN] (teach.mozilla.org)
<img width="1435" alt="screen shot 2015-10-22 at 10 49 34 am" src="https://cloud.githubusercontent.com/assets/1068783/10673443/b1af3438-78aa-11e5-921a-edbfddd9efd1.png">

Email template
<img width="890" alt="screen shot 2015-10-22 at 10 50 07 am" src="https://cloud.githubusercontent.com/assets/1068783/10673444/b4367932-78aa-11e5-8cec-f682946eea22.png">

Can be confused with the main site https://www.mozilla.org/en-US/
<img width="1434" alt="screen shot 2015-10-22 at 10 52 10 am" src="https://cloud.githubusercontent.com/assets/1068783/10673505/130168a0-78ab-11e5-9e3b-f5399fdc6503.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by cassiemc** [comment]
We're going to need input from @hannahkane and @HPaulJohnson here. We will probably want to decouple the wordmark from this and just make a decision about naming and the URL.

**Comment by hannahkane** [comment]
cc @chrislarry33 

I like the idea of having some sort of visual indicator that a web property is part of the "Mozilla Leadership Network." This indicator would go on Teach, but also other properties (Science, News, Advocacy). Perhaps that should be a separate ticket?

@chrislarry33 - since we can likely no longer use "Mozilla Learning Network," since MLN now has a different meaning, what would you suggest we rename this site? Ideally, it would better connect to the url—perhaps Mozilla Teach?

**Comment by hannahkane** [comment]
@chrislarry33 @ldecoursy @HPaulJohnson - this is basically a branding question, so want to get all of your input on this. If we aren't able to make a decision now, I can take this out of the current heartbeat.

**Comment by ldecoursy** [comment]
I would suggest taking it out of this heartbeat. Think we need more time to be thoughtful about how/when we start changing brands (especially with this audience who has been through this with us once before).

**Comment by hannahkane** [comment]
Closing this since it's covered in the IA/branding work happening in other tickets.
