### ISSUE TITLE
[interface element] - buttons

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1388]
**Problems:** 
* inconsistent button styles and hover states
* old maketstrap styles are present
* undocumented button exceptions

**Solutions:** 
* update all makerstrap style buttons
* unify typography *(all caps, colour)*
* unify hoverstates
* unify button sizes *(height, padding)*
* unify corner styles
* document colour
* document button exceptions homepage CTA and promo banner button styles *(less prominent)*

**Seen on:** all pages of [MLN] (teach.mozilla.org)
<img width="1177" alt="screen shot 2015-10-22 at 11 04 58 am" src="https://cloud.githubusercontent.com/assets/2492510/10673828/c3cdb4c6-78ac-11e5-8535-748eab5b6eb2.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
All buttons should be like the "Apply to be a captain" button (yellow, rounded corners, all uppercase and with pushed down hover state).

The 3 buttons over the home page banner would be too overwhelming in yellow so lets stick with blue but update the hover state to have the same interaction as the yellow buttons. So the blue buttons should stay blue (not turn yellow) and it should just push down.

Ignore the Thimble banner button since it we'll be updating that soon anyways.

Please updated all modal buttons to yellow:
- Pledge button
- Apply to be a club captain modal

**Comment by sabrinang** [comment]
![buttons](https://cloud.githubusercontent.com/assets/2492510/13005823/7ceded1a-d139-11e5-90d2-f386992e2adc.png)
