### ISSUE TITLE
Design "Community" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1414]
Rather than take people off-site (straight to Discourse) from a main navigation item, we want to take people to a "Community" page that provides an overview of *all* of the ways to connect with the MLN Community.

url: /community

This will be a top-level nav item, as per design here: https://redpen.io/pm5e582508380c592b

### Content / Copy ###

 * The best way to connect with others in the Mozilla Learning Networks community is through the [Discourse forums](https://discourse.webmaker.org/). Introduce yourself, help test out the latest curriculum modules, or start a new thread about a particular challenge you're facing in your teaching practice.
 * Monthly Mozilla Clubs Open Office Hours [specific details about how and why to participate to come from @amirad, but for now, let's just include a sentence of lorem ipsum as placeholder]
 * [Hive Learning Networks](https://hivelearningnetworks.org/) are a growing constellation of communities around the globe that are championing digital skills and web literacy through connected learning. Find out if there's one near you.
 * Get the latest teaching activities, tips, and news in your inbox every month. Sign up for the MLN Community Newsletter. 
 * Connect with us across the Web. We're on [Twitter](http://twitter.com/mozteach), and our community uses the hashtag #teachtheweb.
 * Share your story. If you teach the Web in your community, we'd love to hear about it! Please share your story using [this form](https://docs.google.com/a/mozillafoundation.org/forms/d/1bOXV1OiF2EKS5KprlnzfFpwaoVNwxLAwN_UEq6hGKqU/viewform).
 * Have a question? Want to be connected with one of our staff or volunteers? Email us at teachtheweb@mozillafoundation.org

**Comment by hannahkane** [comment]
@kgorr @ldecoursy - is this the right page for the newsletter sign-up and archive of previous newsletters?

**Comment by ldecoursy** [comment]
I think so if we can swing it. :)

**Comment by hannahkane** [comment]
OK, added the sign-up link above. Will add archives once we have them. :)

**Comment by kristinashu** [comment]
@hannahkane I'd be nice to have a value proposition to intro the page like we do for clubs and TLM page. Do you have a suggestion for copy?
<img width="1048" alt="screen shot 2015-11-18 at 2 30 44 pm" src="https://cloud.githubusercontent.com/assets/1068783/11256524/295c1efe-8e01-11e5-8641-00a84bf2332d.png">
<img width="1041" alt="screen shot 2015-11-18 at 2 30 58 pm" src="https://cloud.githubusercontent.com/assets/1068783/11256523/295b4768-8e01-11e5-999d-7ebd21b0a8f1.png">

Side note: Do you think we should do this on every main level page? Should I add it to the audit?

**Comment by hannahkane** [comment]
@kristinashu - agree that all top level pages should have a value proposition. For this one, how about, "Join a global community of people teaching the Web"?

**Comment by kristinashu** [comment]
@hannahkane @cassiemc @sabrinang here's where I'm at with the comp: https://redpen.io/p/cnca8a0265383acc93

With the audit in mind I'm trying to keep a simple layout and not introduce new styles but I have incorporated some design suggestions I think we could carry out across the site to address parts of the audit.

Section colour: Suggesting we use teal as a new colour. The lighter section was determined by using a 35% white overlay and the darker section with 10% black overlay - this might be a more streamlined way of dealing with the rest of the section colours.

Banner image: Reduced the vertical height to take up less realestate. Added a value prop (we do this on some of the pages but not all - we should add one to all the primary pages).

Circle icon: Taken from Clubs page but we'll need to design one specifically for this section.

Section breaks (line with diamond): Using grey instead of the section colour to steamline assets.

Font sizes: Trying to reduce the number of font sizes and generally reduce the size (I find some of the existing font sizes quit large).

Bottom 3-up links: Suggesting we make these icons yellow on every page so it matches the button CTA colour we use throughout the site - hopefully this makes them look more like CTAs. Also used regular text instead of italic since we don't really use italic much anywhere else.

Copy note: I shortened the twitter, share and email CTAs a bunch so they could match the style of the other pages.

**Comment by hannahkane** [comment]
Really excellent work, @kristinashu. I like the hierarchy laid out here. Will leave design decisions up to @cassiemc, but I will say the teal is reading suuuuper bright on my screen.

**Comment by kristinashu** [comment]
Thanks @hannahkane I've updated discourse copy and toned down the teal a little (it was pretty bright).

**Comment by kristinashu** [comment]
@cassiemc @sabrinang could you two please take a look and the comp and let me know if you have any design feedback?

**Comment by cassiemc** [comment]
Looks really great @kristinashu. Just a few niggly questions, one about the h2 size, and another about the links in the social ctas. Love the teal and yellow together, looking very fresh, and +1 to the reductions in image size and other changes.

**Comment by kristinashu** [comment]
Great thanks @cassiemc. I've increase the size of the h2s and updated the three bottom links so they each have a text link. For the image hover, we could do a slight zoom in - similar to this first image http://designshack.net/tutorialexamples/imagehovers/zoomandpan.html This effect would loosely align with the icon hover effect on the three bottom links.

@hannahkane I think we're ready to start implementation?

I'll open a separate ticket for the circular icon illustration.

**Comment by hannahkane** [comment]
Thanks, @kristinashu. Can you add any necessary assets to the implementation ticket - #1434?

Closing this.

**Comment by amirad** [comment]
@hannahkane I placed Mozilla Clubs info in one of our github pages http://mozilla.github.io/learning-networks/clubs/#officehours 

Is that enough to add to the community page? do you need anything else?

**Comment by hannahkane** [comment]
@amirad - I think that copy is good. @kristinashu - possible to update the mockup with this copy to see if it fits well?

**Comment by kristinashu** [comment]
Updated! It was getting a little long so I left out the date and time - people will have to click the link to find out when. 

Also noticed we're saying the word 'or' twice "Want to share what your Mozilla Club is doing or or where you need help?" on http://mozilla.github.io/learning-networks/clubs/#officehours

![teach-community-04 2x](https://cloud.githubusercontent.com/assets/1068783/11354639/14b52586-9202-11e5-81e9-a03d634159bc.jpg)

**Comment by amirad** [comment]
Ops thanks for the catch @kristinashu - just made an update!

**Comment by hannahkane** [comment]
Awesome. Closing this ticket.
