### ISSUE TITLE
Build Community page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1434]
Design to come from #1414 

Newsletter sign-up list is same end point as Pledge—that is, those addresses should go into the same BSD list.

**Comment by mmmavis** [comment]
@kristinashu do you mind attaching the .ai file and assets here? Thanks!

**Comment by kristinashu** [comment]
@mmmavis here's the ai file https://drive.google.com/open?id=0B2irLVDJivhLMS1Vdm9jd1BwNnc

**Comment by kristinashu** [comment]
@mmmavis here are the assets: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLYVF0Nm5vS2VvelU&usp=sharing

Let me know if you need anything else!

**Comment by mmmavis** [comment]
@hannahkane 
Since we are using the same mailinglist as the pledge signup, users will be redirected to https://teach.mozilla.org/?pledge=thanks after (it's controlled by BSD and there can only be one destination). Without touching the config on the BSD end I think the easiest solution is to make the text on the Thank You modal more general?

![screen shot 2015-12-18 at 2 19 15 pm](https://cloud.githubusercontent.com/assets/2896608/11908594/5a746b60-a592-11e5-8fe9-c90afcefd6dd.png)

**Comment by hannahkane** [comment]
Hmm...ok. How about changing the title to "Thanks for your interest!" I think we can keep the main message the same.

**Comment by mmmavis** [comment]
Yea, I can do that.  What should we change the sample Tweet to? It's currently "I just pledged to #TeachTheWeb! https://teach.mozilla.org"

Or if creating new forms on BSD is still an option I can do that and point the forms to the same pledge mailinglist. This way I can have the Thank You url redirected to a different place.  /cc @adamlofting

**Comment by hannahkane** [comment]
Tweet could be "I love to #TeachTheWeb! https://teach.mozilla.org"
