### ISSUE TITLE
Write value props for banner area

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1446]
Based on #1414 and build #1434 we need to add a value prop intro to every primary page.

Pages that need copy added:
- https://teach.mozilla.org/activities/
- https://teach.mozilla.org/events/ 
- https://teach.mozilla.org/tools/ (will be adding a banner image)

@hannahkane are you able to write these? Then it can go straight to @mmmavis for implementation.

**Comment by hannahkane** [comment]
Since the updated sidebar won't include the blurbs we currently have on the sidebar, wondering if we can just use them.
* https://teach.mozilla.org/activities/: Activities and lesson plans to get you started
* https://teach.mozilla.org/events/: Host a one-time event or workshop
* https://teach.mozilla.org/tools/ (will be adding a banner image): Open source software to teach and learn the Web

**Comment by kristinashu** [comment]
Ahh smart!

**Comment by hannahkane** [comment]
Think we can close this, right, @kristinashu ?

**Comment by kristinashu** [comment]
Yeah, ready to implement!
