### ISSUE TITLE
Deadline: First week of January - Update copy on Gigabit site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1449]
Currently blocked on final copy, which is being edited [here](https://docs.google.com/document/d/1qfy0RsEzGRr9HLGDL1qah5iqwRSQY4T1ywWDHI9Y0io/edit).

@LindseyFrost - can you please drop a comment here when the copy is finalized?

**Comment by LindseyFrost** [comment]
@hannahkane Landing page copy is done and ready to go.  Apply page content is blocked by (1) updated rules terms and conditions (though will probably be updated at same link) and (2) need for updated iStart link.  Landing page can be updated, however, and will try to resolve these other issues next week (blockers noted in red on the content Google doc).

**Comment by hannahkane** [comment]
Thanks, @LindseyFrost.

@mmmavis - I'm adding this as a p2 to this heartbeat. Let's chat about it tomorrow at stand-up.

**Comment by mmmavis** [comment]
It's been probably almost 2 years(?) since I touched the [mozilla.org aka "bedrock" repo](https://github.com/mozilla/bedrock).  If I remember correctly and the rules haven't changed - the team triages their tickets weekly and they don't push on Fridays unless it's an urgent fix. 

It's hard to estimate when and how long it will take the mozilla.org team to review our PR as it depends on the team's existing priority and capacity.  If we would like the Gigabit page to be updated before or on a specific date, we should give Jennifer Bertsch / Mike Alexis a heads up soon.

**Comment by hannahkane** [comment]
Thanks, @mmmavis. I'll be in touch with Jennifer and Mike now.

**Comment by hannahkane** [comment]
@LindseyFrost - tried to clarify the doc for Mavis. Moved all notes to the bottom, and added a Table of Contents at the top. Also added two questions for you to answer as soon as you can. Thanks!

**Comment by hannahkane** [comment]
@mmmavis - when you have a moment, can you take a look and see if the doc makes more sense now? Happy to talk through it over Vidyo, too.

**Comment by hannahkane** [comment]
I think this is unblocked, so removing that label now.

**Comment by mmmavis** [comment]
@hannahkane I'm changing this to P1 - I wanted to get this done early for the mozilla.org team to review.

**Comment by LindseyFrost** [comment]
@hannahkane @mmmavis  Terms and Conditions should be finalized by legal this week, and I will update the google doc as soon as this is complete.  Thank you!

**Comment by hannahkane** [comment]
@LindseyFrost - will we also have to update the T&C page, or will we be given a new page to link to?

**Comment by LindseyFrost** [comment]
@hannahkane @mmmavis It looks like we are going to have to update https://www.mozilla.org/en-US/gigabit/terms/ because of some required changes from legal.  Trying to get these as quickly as possible and will update you as soon as I can.  Apologies!.

**Comment by mmmavis** [comment]
FYI, this is the Bugzilla ticket that I just created: https://bugzilla.mozilla.org/show_bug.cgi?id=1229957

**Comment by hannahkane** [comment]
Moving to next heartbeat to finalize.

**Comment by mmmavis** [comment]
@sabrinang can you attach the logos for Hive KC and Hive CHA here? I can't find them in Google Drive.

**Comment by sabrinang** [comment]
Hive CHA: https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eb3EzTm9kYmFWUkk/view

Hive KC: https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eMnNKOEJubmQycEk/view

**Comment by sabrinang** [comment]
those are from the hive learning networks site

**Comment by mmmavis** [comment]
Thanks for looking up the logos, @sabrinang !

For the layout in Types of Support section (see screencaps below) I wonder if we can avoid using table since wide table doesn't look good on smaller screens - it either get cut off or squeezed (unless we want to enable horizontal scrollbar which is unlikely the case)

![gigabit-apply-desktop](https://cloud.githubusercontent.com/assets/2896608/11857539/f6285908-a40d-11e5-809a-e2c450299297.png)

![gigabit-apply-mobile](https://cloud.githubusercontent.com/assets/2896608/11857540/f6296fe6-a40d-11e5-8833-ea5fcabc22fa.png)

**Comment by sabrinang** [comment]
Example of how it can look on mobile devices
![mozilla_gigabit_mockup-table-example](https://cloud.githubusercontent.com/assets/2492510/11878997/a6a8afb8-a4ad-11e5-8edd-6a65dfd93a66.png)

CSS reference: http://codepen.io/pixelchar/pen/rfuqK

**Comment by mmmavis** [comment]
For reference:
My PR to mozilla.org has been filed and waiting for review: https://github.com/mozilla/bedrock/pull/3667

**Comment by hannahkane** [comment]
Yay! Thanks, @mmmavis.

**Comment by hannahkane** [comment]
Moving this to January milestone, since there's no more to be done on our side.

**Comment by mmmavis** [comment]
finally live! woohooo https://www.mozilla.org/gigabit/ :tada:

**Comment by LindseyFrost** [comment]
Woooooo!!!  So excited!  Huge thanks to you all!!!

**Comment by hannahkane** [comment]
Looks awesome! OK to close?

**Comment by mmmavis** [comment]
yup yup!
