### ISSUE TITLE
ReactDOMComponent warnings raised from `npm test`

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1491]
We get several ReactDOMComponent warnings from running `npm test` now, e.g., 

```
Warning: ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as `render` did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className). This DOM node was rendered by `ModalRemoveYourClub`.
```

This is probably due to our recent React version bump to v0.14.  We should visit the test files and fix the code.

relates to https://github.com/mozilla/teach.mozilla.org/issues/1460

/cc @Pomax

**Comment by Pomax** [comment]
I've been able to remove all the warnings except the ones in the clubs modal file, which talk about a `getDOMNode` being called, even though there is no code anywhere that does, so it's a deeper error. I'll hunt it down... =_=

**Comment by Pomax** [comment]
Turns out these warnings are generated by [react-input-autosize](https://github.com/JedWatson/react-input-autosize), which is still using React 12 code, so we should be able to solve this issue automatically once the code for that module [becomes React 14 compatible](https://github.com/JedWatson/react-input-autosize/issues/33)

**Comment by Pomax** [comment]
Nope, looks like it was actually `react-select`, updating that to 0.9.1 solve solve the warnings (but breaks our tests. Its semver seems to treat the minor release number as a major release number)

**Comment by Pomax** [comment]
we fixed this
