### ISSUE TITLE
Consider adding a "Curriculum Frameworks" page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1499]
With consideration of adding Web Literacy v2.0 under the “Curriculum” section *(what we are thinking of renaming Activities)* to the site, we should consider a broader Curriculum Frameworks section to be inclusive of other existing frameworks that exist for curriculum that would influence our future curriculum database too *(for example, [Participation Team’s Participation Leadership v0.1](http://tiptoes.ca/wp-content/uploads/2015/08/2015-08-28_1244.png))*.

We can also consider including values (from [teach like mozilla](https://teach.mozilla.org/teach-like-mozilla/)) and personas (from [participation personas](http://education.mozilla-community.org/modules/about/personas/) & [web lit whitepaper](https://docs.google.com/document/d/1sP_nrYtkoZEyAOzfIxAFIgxBRq6T2ZGoBB_iuWYNyQI/edit) )

What other frameworks exist for curriculum we are producing?
How should we contextualize and differentiate these frameworks from one another to be useful for users?

Thoughts and feedback?  @chadsansing @anmechung @emmairwin

/cc @hannahkane 

Related Tickets: consideration of removing TLM #1498, web lit 2.0 design #1457

Redpen for reference: https://redpen.io/wm0ac2ae5cb51ed9f9

**Comment by jgmac1106** [comment]
I would suggest renaming activities curriculum.

I would also elevating the web literacy map as a top level nav link rather
than a sub-link. That is the framework that underpins the curriculum and
the badges. It is what Mozilla believes you need to know in order to read,
write, and participate on the web.

In terms of Teach Like Mozilla, while I contributed I was never a fan
myself. Its basically good pedagogy. Good pedagogy, but branded. I would
rename the TLM section "professional development" or "leadership and
advocacy." This would be the place where you include the curriculum
designed for the teachers, club captains,educators, and advocacy. The
curriculum tab would be for the learners.

I hate to keep harping back to the teachtheweb survey but professional
development was one of the major wants of the audience. Both the content
and navigation should reflect this.

**Comment by chadsansing** [comment]
Great prompts, @sabrinang. I think we need to discuss nav elements and site organization more broadly within MoFo and MozTeach. In the absence of lead.mozilla.org, it's unclear to me how we should structure teach dot. 'Leadership' and 'web literacy' both resonate with me as parent-level nav elements, but web literacy is something leaders model and teach - a child-function of the leader object. The gerunds we usually use with leadership - e.g. convening, facilitating, teaching - don't call out web literacy, either, yet. Lots to unpack. Maybe it would be easiest to get lead.mozilla.org built, after all :)

We could use 'curriculum' instead of 'activities,' but in considering other frameworks, regardless of what we call the page, are we also thinking of different kinds of artifacts to share there? Like, would we link to a standalone Thimble project in between two curriculum modules? I think I need more help with what 'framework' means here, @sabrinang.

**Comment by hannahkane** [comment]
Important context: when we imagine the "Curriculum" page, we can think of it in the context of the to-be-built Curriculum database that will allow us to pull in a variety of curricula, not just Web Literacy. Given that, I think it makes sense to include the Participation Leadership framework, and any others that exist. Ideally, each framework makes use of the curriculum database—I know that's what @sabrinang is thinking about for the Web Lit framework.

Suggest we limit this ticket to the specific question of whether we should have a "Curriculum Frameworks" page, and move broader conversation about terminology, TLM, and lead.m.o to separate tickets. I know they're related, but I think it's best to isolate issues wherever we can. (IMO!)

**Comment by chadsansing** [comment]
I hear you, @hannahkane. I think these things are too interrelated in my mind to give Y/N feedback on a frameworks page. Imagining a test to determine who would look for a frameworks page instead of either a)curriculum or b)leadership materials.

**Comment by hannahkane** [comment]
@chadsansing - I don't think a curriculum frameworks page would be *instead* of a curriculum page, but rather in addition to. In fact, I'd guess that the most frequent entry point to the frameworks page would be *from* the curriculum database.

**Comment by chadsansing** [comment]
I'm just having trouble considering external use cases and I worry some about mission creep, but I could be approaching this all wrong. I think we should also talk about this on a call.

**Comment by hannahkane** [comment]
I think we might be over-complicating this. We currently have a Web Lit Map page on the site, which is the framework that accompanies our Web Lit curriculum. I'd like for us to move those two pieces closer together in the site's architecture, hence moving the Map to a sub-item under Curriculum. 

This ticket is really asking if we should make that page more generic—"Curriculum Frameworks"—and include other frameworks that correlate to other curriculum sets we'll likely be including in our view of the database. 

I think it's likely the Teach site will show a view of the database that includes both the Web Lit curriculum AND the participation curriculum, so it makes sense to include both frameworks. (If that's not the case, then I'd suggest we keep the page limited to the Web Lit Map.)

**Comment by chadsansing** [comment]
I see. I guess I'd go back way to @jgmac1106's comment to call such a page 'Curriculum' and link to hubs under that. Sorry for the confusion! 'Frameworks' makes me think of pedagogical approaches like contructivism, etc.

**Comment by anmechung** [comment]
Jumping in on this thoughtful conversation.  +1 to jgmac1106 early comment: "elevating the web literacy map as a top level nav link rather than a sub-link. That is the framework that underpins the curriculum and the badges. It is what Mozilla believes you need to know in order to read, write, and participate on the web." Agree that it should be the philosophical underpinnings/principles of the curriculum, credentials etc.  AND +1 to @hannahkane of moving the Web Lit 2.0 map as a sub-item under curriculum, and consider calling it "curriculum frameworks" which IMO gives us more flexibility to include other curriculum such as the participation, and deeper dives in the future.

**Comment by hannahkane** [comment]
Cool. Thanks, everyone, for the conversation. While I'm a little bit confused about whether we see the Web Lit Map as a top level item or a sub-item, I'm actually not concerned about that level of detail at this point. I think this ticket was really about whether we see Teach.m.o including curricular content beyond Web Literacy (e.g. Participation), and I think we definitely do.

Going to close this ticket, but we'll continue to talk about site architecture and content in the new year.

**Comment by anmechung** [comment]
Sorry for the confusion - at this point, I agree with jgmac1106 that web literacy 2.0 map should be a top level nav link.  Looking forward to continue discussing in the new year!

**Comment by emmairwin** [comment]
I would say that Participation aligns well with the web literacy map- especially if three pilars are read/write participate.
* Design contribution for example covers :  Design (under build), perhaps accessibility(under build), collaborating and open practices (both under participate)collaborating and open practices (both under participate)
* Code contribution to connected devices:  web mechanics (explore), coding/scripting (build),  and open practices (both under participate)

So, if web literacy is top level, then I wonder how we could make room for activities, and outcomes that actually contain one or more literacy as participation does.  cc/ @jgmac1106

**Comment by emmairwin** [comment]
"Important context: when we imagine the "Curriculum" page, we can think of it in the context of the to-be-built Curriculum database that will allow us to pull in a variety of curricula, not just Web Literacy. Given that, I think it makes sense to include the Participation Leadership framework "

yes!  complimentary.  we are testing the framework in singapore, and my have strengthened vision afterwards.

**Comment by jgmac1106** [comment]
I agree. Though don't want to muddy the ticket in terms of web literacy and
participation being subpages under a curriculum framework page.

I may not be aware of all the meta conversations occuring in terms of web
properties.

If teach.mozilla.org is going to be a stand-alone destination for MoFo web
literacy than the map makes sense as top nav.

If it will include the leadership and advocacy  as well as learning I would
suggest two different main links rather than a collection of curriculum
frameworks.
