### ISSUE TITLE
Client ID for webmaker

### ISSUE THREAD

**Issue by issasouktel** [mozilla/teach.mozilla.org#1519]
I have an issue with authenticate user, when the backend API redirect the user to webmaker the client-id in url is sent as None, i have to get client Id for webmaker 

webmaker url 
https://id.webmaker.org/login?client_id=None&response_type=code&state=NtDoNES00uER4gDqx3kD4GO9GHT2OKXU&scopes=user%20email

**Comment by Pomax** [comment]
You mean redirect back to `teach.mozilla.org`? (webmaker is a product offering). The usual way we do this is to make the clientid an environment variable (loaded either by processing an `.env` file with something like [habitat](https://www.npmjs.com/package/habitat) --making sure to add `.env` to the gitignore-- or having it set as a real current environment variable).

You will need to create a client id, tied to the callback URL you need, in the [id.webmaker.org](/mozilla/id.webmaker.org) postgres oauth database, in the `clients` table:

```
webmaker_oauth_test=> \d clients
 client_id         | character varying | not null
 client_secret     | character varying | not null
 allowed_grants    | jsonb             | not null
 allowed_responses | jsonb             | not null
 redirect_uri      | character varying | not null
```
If you've set up a local id.webmaker.org instance and told it to run its tests, you should have some demo data in there that can be used as example for how to create a new client id with associated callback url:
```
webmaker_oauth_test=> select * from clients;
 test      | test          | ["password", "authorization_code"] | ["code", "token"] | http://example.org/oauth_redirect
 test2     | test2         | ["authorization_code"]             | ["code"]          | http://example.org/2/oauth_redirect
 test3     | test3         | ["password"]                       | ["token"]         | http://example.org/3/oauth_redirect
```

It might be easiest to set up the https://github.com/cadecairos/webmaker-docker instance so that you have all the login/id/etc services running in a container, and then create the necessary client id in that container.
