### ISSUE TITLE
Create "Pitch Deck" for Hive Chicago Buzz

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1599]
Let's create a short pitch deck that can be shared with potential participants and partners—to give them a sense of what the event is about and what value they'd get from being involved.

(Note: this could be in lieu of a 2016 infographic, rather than in addition to)

@omnignorant - can you provide the kind of content you'd want to include?

/cc @vazquez

**Comment by hannahkane** [comment]
@erikad - wondering if you'd want to move this over to Convenings work? Seems like it fits best there.

**Comment by edrushka** [comment]
Wondering about the timing of this. Is there a reason we're doing this now, and not closer to the call for session proposals for the next HCB?

**Comment by hannahkane** [comment]
Flagging @omnignorant to answer that very good question. Might have been a remnant of when this was going to be the "Create 2016 infographic" ticket. Since it's morphed into something with the specific strategic purpose of helping to engage future participants and partners, perhaps it should happen later, as @edrushka suggests.

**Comment by omnignorant** [comment]
I dunno. I haven't been able to stay on top of this because of a series of unexpected obligations the last two weeks, BUT my thinking was that

* 9 months from now, we'll have to go back and dig around to surface what made this event special. In principle, if we made this deck now, we'd be pre-empting that work with ideas still fresh in mind.
* a template approach could be useful for other events coming up this year;

If this doesn't feel like a piece of work that has more broad applicability, let's close it.

**Comment by hannahkane** [comment]
@edrushka - what do you think? Should we move to convenings, close, something else?

**Comment by edrushka** [comment]
I'm going to close and may re-open when the Convenings teams starts to tackle creating templates. @omnignorant if you have bandwidth to run with this now, please feel free to re-open. I'd be happy to review.
