### ISSUE TITLE
Clean up wiki links

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.mozilla.org#1625]
@hannahkane @kristinashu Can we delete a couple pages in the wiki - they seem out of date? Or should we update them?

sitemap: https://github.com/mozilla/teach.mozilla.org/wiki/sitemap
State-of-the-Site-Architecture---March-3-2015: https://github.com/mozilla/teach.mozilla.org/wiki/State-of-the-Site-Architecture---March-3-2015

Also not sure if 'Club approval process' is up-to-date: https://github.com/mozilla/teach.mozilla.org/wiki/Club-Approval-Flow

**Comment by hannahkane** [comment]
Thanks for this ticket, @cassiemc.

Removed the sitemap because it is out-of-date. Not sure that a new one is needed right now.

@Pomax - would you be up for updating [State of the Site Architecture](https://github.com/mozilla/teach.mozilla.org/wiki/State-of-the-Site-Architecture---March-3-2015), and/or adding a new note reflecting the current stat eof things?

Clubs approval process is actually up-to-date.

**Comment by yash14123** [comment]
Any other things to be removed. I can help with that. :)
