### ISSUE TITLE
Update Web Literacy Page with Web Literacy 2.0

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1659]
Currently, web literacy is shown here https://teach.mozilla.org/activities/web-literacy and based on #1603 wireframes ([see redpen](https://redpen.io/p/to351d853022563354)) we need to make the following updates for Web Literacy 2.0:

- Web Literacy will become a primary navigation item on the teach.mozilla.org site located below "Teaching Activities" and above "Leadership Opportunities". 
- It will contain a secondary navigation item called "21st Century Skills" ([see redpen](https://redpen.io/gr3a96536189fa25cd))
- Include the new interactive Web Literacy visual with 21st Century skills colour legend
- Include new copy from definitions in the concept paper ([see gdoc](https://docs.google.com/document/d/1Cs0rAd7zZqV5pNovTbjqF-F0eM6Qw0etnG5SOWa4jVk/edit)) and corresponding activities from web lit basics ([see gdoc](https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#))

We need to brainstorm and discuss how to implement the interactive web literacy graph that considers... how it can work responsively, have short page load time, clear transitions between sections, how it could be localized etc.

Related issues: #1603 (wireframes)
cc/ @mmmavis @Pomax @flukeout @hannahkane

**Comment by hannahkane** [comment]
Adding to this milestone only because I'm hoping to have the brainstorm and discussion this milestone; but the actual implementation will start next heartbeat.

**Comment by Pomax** [comment]
I'm up for discussions!

**Comment by hannahkane** [comment]
Rolling this into the next heartbeat where the bulk of this work will happen.

**Comment by Pomax** [comment]
Started a branch https://github.com/Pomax/teach.mozilla.org/tree/weblitcircle on my repo for this, and integrated the circle nav I'd been playing around with, so things currently look like this:

![capture](https://cloud.githubusercontent.com/assets/177243/13480344/104cde9c-e092-11e5-8d0d-563d044ae15d.PNG)

**Comment by Pomax** [comment]
copy in https://github.com/MozillaFoundation/plan/issues/742#issuecomment-191508792

**Comment by Pomax** [comment]
The circletree code is now on npm at https://www.npmjs.com/package/react-circletree, using an `onToggle` function described in its readme for knowing what a user clicked on.

**Comment by Pomax** [comment]
@scottdowne will be taking this issue, as he has some time to work on this, whereas I'm also trying to get badges sorted out.

**Comment by ScottDowne** [comment]
@sabrinang I'm looking for things like icons and colour codes (I think just the orange, from what I have seen).

**Comment by Pomax** [comment]
@thecount note that we pull the colours from `variables.less`, so any colours should be named and pulled from there, rather than be hardcoded hex or rgb values.

**Comment by ScottDowne** [comment]
@Pomax Ah, so the colour I'm looking for is probably already in there :)

**Comment by Pomax** [comment]
might very well be!

**Comment by ScottDowne** [comment]
Haha, It's been a long time, but I totally remember this: https://github.com/mozilla/teach.mozilla.org/blob/2be4cc37fc47b14839930e58939b765dcd692a84/less/variables.less#L17

@radicalPumpkinOrangeSidebarColor

**Comment by ScottDowne** [comment]
Current state: https://enigmatic-oasis-60628.herokuapp.com/web-literacy

Mostly missing style bits and images/icons.

**Comment by sabrinang** [comment]
Neat! I'm going to check it over today and give you feedback/assets.

**Comment by ScottDowne** [comment]
I'm able to get all the activity/kit assets either in the existing repo or from the project themselves.

**Comment by Pomax** [comment]
We're currently lacking a way to get back to the "main" view, it would probably make sense to have clicking the center "web literacy" dial undo any filtering we did to reset the view.

I imagine they do, but should all the skill selections change the URL, too @sabrina? So that we get urls like `https://enigmatic-oasis-60628.herokuapp.com/web-literacy/read/` and `https://enigmatic-oasis-60628.herokuapp.com/web-literacy/read/synthesize` etc?

**Comment by ScottDowne** [comment]
@Pomax yeah, we should be able to link to these (and use the back button) but might be a p2?

@Pomax to be able to listen for clicks in the center, I'll need to add that functionality to the circle code itself, right? Nothing right now triggers that click event?

**Comment by Pomax** [comment]
indeed, let me add that to the circletree code right now.

**Comment by sabrinang** [comment]
**Feedback for 21st Century Skills Page**

Banner Image: https://drive.google.com/open?id=0B4Q8pzCpDS_eRWdmN25BVFNCSXM
Banner Image (@2x): https://drive.google.com/open?id=0B4Q8pzCpDS_edkZkRkQwNWRwVzA

Paragraph copy can be found here: https://github.com/MozillaFoundation/plan/issues/742#issuecomment-191508792

@Pomax - It would be ideal to have skill sections to have URLs to be linked to. 
![screenshot-link](https://cloud.githubusercontent.com/assets/2492510/13754669/14dbbc34-e9d5-11e5-8dab-dbcbed3884e0.png)
For the example above, each link for the read, write and participate section should be a separate and link back to the definition on the Web Literacy 2.0 page. For example, “Read: Search, Navigate, Synthesize, Evaluate” Search is linked to `https://enigmatic-oasis-60628.herokuapp.com/web-literacy/read/search` 

Read Whitepaper link: http://mozilla.github.io/content/web-lit-whitepaper/

**Comment by sabrinang** [comment]
**Colours**
grey (lightness 60%) `#F1F0F1`
grey (lightness 55%) `#E3E3E4`
grey `#56565A`
nightly blue `#1F366C`
aurora purple `#95368C`
firefox orange `#F26C23`
flame yellow `#FFCD02`

![web-literacy_colours](https://cloud.githubusercontent.com/assets/2492510/13755600/43a229dc-e9d9-11e5-8551-d854e4bd5f8a.png)

For context, colours are from unified palette and testing done on this issue: https://github.com/MozillaFoundation/Design/issues/152#issuecomment-196460839

**Comment by Pomax** [comment]
hm, this feels like a really serious, dark (emotionally) palette, is there leeway to go with something lighter or more lighthearted?

**Comment by sabrinang** [comment]
Yes there is leeway to adjust these as we are testing out this unified palette. Nothing is set in stone as colours have been tricky. We can tweak the lightness on these colours so they have a more pastel, lighter feel that the initial mockup had. +1 to the purple and blue too and with the white gaps in between it makes it hard to differentiate and eliminating the space in between will help too.

I came about this palette trying to see what looked good across various use cases but I agree that the original set is looking dark with the predominant navy. I'll try some lighter palettes but I have a feeling they won't be as distinguished in some colour-blind tests.

Any recommendations on accommodating users with colour-blindness or for print (the grey bg disappear and sections don't look separate)? It's been tricky to choose a palette that looks distinguished and pleasant across these contexts so maybe having different palettes available would be an idea since one size can't fit all.

**Comment by sabrinang** [comment]
@ScottDowne Thanks for flagging the confusion on filtering in [redpen](https://redpen.io/eu4c03e71cec9055c7?showing_comment=1655076)!

Yes, I agree that you should be able to find all activities under a competency regardless of its verb. I think for the most part ignore the verb will work and display it under what is assigned in the doc here: https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit# 

Looking at it closer I'm not sure how this doc was sorted…  For example, #allthezstickerz activity is under **Participate** and has competencies from all 3 literacies (**Read:** Synthesize, Evaluate **Write:** Code, Compose, Remix **Participate:** Connect, Open) but it has the most from **Write** but doesn't belong to it so I'm not sure how these are determined.

For the literacy verb pages (read, write, participate), I am organizing it by [that document](https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#) regardless of its competencies - @chadsansing can you confirm that this is how you want the activities to be displayed with the web lit map?

**Comment by sabrinang** [comment]
@ScottDowne I remade the images as line art and placed the .svg files here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eMTJTYlZHNWpuaGs&usp=drive_web
<img width="1377" alt="screen shot 2016-03-14 at 4 52 50 pm" src="https://cloud.githubusercontent.com/assets/2492510/13763671/3bf27c06-ea05-11e5-8b73-8e7f74c79daa.png">

**Comment by hannahkane** [comment]
comment from @davidascher: "re: web literacy map -- good progress, but a request: we need to adjust the layout.  On a 13" laptop, all of the text about literacies is below the fold, and so it's basically impossible to see the effect of clicking on the map itself.  I was literally puzzled as I was clicking around, and I was aware of the plan."

I've noticed this, too, and remember discussing it earlier. @sabrinang or @cassiemc - do either of you remember if we landed on a solution for this?

**Comment by sabrinang** [comment]
Yes this was brought up during a crit and I believe a solution was to reduce copy above graph so it sits higher on the on the page and as well as considering when a section is selected to transition down to where the heading/definition is below (anchored link).

**Comment by chadsansing** [comment]
@sabrinang, it's definitely a balancing act between tagging every activity with read, write, and participate and choosing one of those verbs that best captures the spirit of the activity. For example, #allthestickerz is tagged with participate because even though it has a lot of "write" competencies, the ultimate goal there is to remix the web with goggles using stickers you create to comment on other pages' conten - you are creating (or writing) to participate. I routinely make that kind of call in the design work, but would welcome other thoughts on labeling - another issue/thread for sure.

@anmechung and I have both been over the crosswalk document you cite - it's useful for labeling those activities, but not for organizing the web lit map itself, if that makes sense. For all things that have to do with sorting the web lit map itself, I defer to @anmechung.

**Comment by sabrinang** [comment]
I have met with @anmechung to confirm that we do display activities connected to competency regardless of the verb and list it under the verb as well that Chad has assigned to it. We want to emphasize that the main priority right now is displaying the definitions and include some recommended activities as actionable content to show how it is connected. In the long term, all the activities will be sorted in some way like a curriculum database but that still needs to be figured out.

**Comment by anmechung** [comment]
Agreed with @sabrinang.  In the future, activities in end up in the curriculum database that Mozilla curates may indicate the web literacy skills with a link to the entire web literacy map.

**Comment by xmatthewx** [comment]
Implementation doesn't match the responsive spec and the chart is unreadable on mobile. But, even with that spec, screen height will divide the interaction from the results as @davidascher pointed out. 

I recommend that the designer and dev team up to make a simple responsive wireframe in Thimble, to figure out layout and interactions across screen sizes.

**Comment by ScottDowne** [comment]
@xmatthewx 

It's using existing components for layout, so it is doing what those components already do on mobile.

Although I noticed the circle nav is completely hidden on mobile, which, I thought was an intended change based on feedback after the redpens where made. We can tweak.

**Comment by xmatthewx** [comment]
Cool. Thanks @ScottDowne. Sorry for the fly by comment. Here's a screenshot via FF Dev responsive tool. 

![screen shot 2016-03-16 at 11 09 39](https://cloud.githubusercontent.com/assets/53411/13827520/4cab7388-eb93-11e5-8cf9-0b8694f9a045.png)

**Comment by ScottDowne** [comment]
@xmatthewx Ah, I didn't even notice it's showing it really small. Yeah, that's def not an intended design.

I'll fix it.

**Comment by hannahkane** [comment]
In the default page - before the user has selected anything, should the order be "Read, Write, Participate" instead of "Write, Read, Participate"? - @anmechung

**Comment by anmechung** [comment]
@hannahkane yes, order should be read, write, participate

**Comment by anmechung** [comment]
@sabrinang @ScottDowne Thank so much for paying such great attention and catching discrepancies!   I updated the cross-walk between web literacy map and activities.   https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit# 
@chadsansing can you take a quick look?  I read through each activity and matched with relevant skills as best I could.  FYI - For the purposes of the activities, I don't think we need to match to skills buckets/categories of "read, write, and participate" (formally named verb in the google doc chart)

@sabrinang - can you update the activities  (left hand column on each of the activity pages) and change from Web Literacy Competencies to “Web Literacy Skills” with corresponding skills in the 3 column from left.  Also  add “21st Century  Skills” header (similar to Web Literacy Skills) underneath with corresponding 21st Century Skills in far right column.  At some point, @chadsansing or myself will need to go into each activity and tweak content on right hand side a bit to match updated web literacy map. 

Note: To be clear about terminology, the web literacy skills are search, connect, remix, etc.  The competencies are for example (search as the skill example): 
- Using and revising keywords to make web searches to find information more efficiently. 
- Discovering information on a given topic spread across a website.
- Detecting information in a website using the internal search engine.
- Evaluating questions and search keywords while considering the purpose of search and obtained results.
- Finding real-time or time-sensitive information using a range of search techniques.
Spoke with @sabrinang to makes this more clear in the white paper.  
@chadsansing if you could use terms in this way as you develop curriculum template, that would be great!

Similar pattern for 21st Century Skills of creativity, problem-solving, collaboration, and communication
The competencies are here and will correspond to badges: https://docs.google.com/document/d/1u9j28HqV8QMsk-foS1r0N-tVtmcLTLsGz9m7eKcT_eU/edit

As we are nearing the end, my sincerest apologies, but @sabrinang and @ScottDowne good thinking and questions got me to think that I need to integrate specific 21C competencies into the white paper rather than as a link to chart particularly since badges/credentials are being built right now for them.  I've added the text on bottom of page 10 (in red) to the white paper https://docs.google.com/document/d/1Cs0rAd7zZqV5pNovTbjqF-F0eM6Qw0etnG5SOWa4jVk/edit.  I've also added in 5 places to clarify skills and competencies (also in red): top of page 4, middle of page 5, top of page 8, foot on page 8, middle of page 10.

Hope this all makes sense - happy to further clarify.

**Comment by jgmac1106** [comment]
@anmechung is that a change in terminology? We have always said their are
three strands, then the competencies, and then the skills under those
competencies.

**Comment by anmechung** [comment]
@jgmac1106 Yes - read, write, participate are strands (thanks for the reminder)!  As for skills and competencies terminology, they as we know are often used interchangeably.  At Mozilla, I've always heard them referred to as web literacy skills and competencies, and assumed that skills was the higher level, and competencies underneath. However, I may have not looked in all the right places. So, I looked through various definitions, and landed on skills are the "what" and competencies are the "how." This combined with the fact that we and others refer to them as the 14/15 web literacy skills, and that this aligns with the 21C skills  language landed the terminology where it is now.

**Comment by anmechung** [comment]
spoke with @chadsansing and he mentioned web lit II activities have been migrated ot new template since the original crosswalk.  @chadsansing will update the crosswalk for web literacy map and web lit II basic skills, and each activity page.   https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#

**Comment by sabrinang** [comment]
@anmechung I will file a separate ticket for updating the activities (updating “Web Literacy Competencies” to “Web Literacy Skills” and adding “21st Century Skills” ) as I have not handled any of activities so far and it might be something @chadsansing is familiar to do

I will also file a separate ticket to update these changes in the white paper too.

You have added competencies to 21C Skills as well on the white paper so we can surface this content on the page itself to be cohesive (since we have done so for the web lit skills) and I'll create a mockup to show this copy in context. 

@anmechung is this text finalized or are changes still being made in the google doc? (unsure if people are currently reviewing/editing this)

**Comment by sabrinang** [comment]
After looking over the content in the crosswalk and the inclusion of 21C skill competencies, I addressed a few questions that came up with @anmechung. Initially, collaboration we’re 5 separate types (audience & awareness, communication, conflict resolution, use of collaboration technology and responsibility & productivity) and noted that the redundancy of communication could be confusing as it is another 21C Skill already. Also this would require further defining collaboration types in tags/filter since we distinguish just “collaboration” currently in activities and graph. We decided to collapse collaboration badges into one and distinguish subsections in competencies instead which would further simplify how 21C skills are described and not needing to introduce new 21C skills or tiers within them. 

I will update [mockup](https://redpen.io/gr3a96536189fa25cd) to reflect this and ensure whitepaper content (#1739) will update to match.

**Comment by anmechung** [comment]
@ScottDowne @sabrinang I double-checked web literacy skills language, and made no changes.   Here is the language (pulled from web literacy paper) in case you need it:
https://docs.google.com/document/d/1emSA0TonNbzIxjQpSkJu1wkAhAKbn5eiHFKZFS-mQa8/edit

**Comment by ScottDowne** [comment]
Pretty sure it's safe to close this now :)
