### ISSUE TITLE
Create a process for updating video embeds and etherpads for the Mozilla Curriculum Workshop

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1693]
From @chadsansing:

@kgorr, @poh, and @flukeout, can you develop a process and timeline between Mozilla Curriculum Workshop episodes for embedding a new broadcast and etherpad for upcoming episodes? I can have copy ready to go based on what we decide is the technical process here.

cc @amirad, @ldecoursy, @hannahkane

**Comment by hannahkane** [comment]
@KGorr @poh @chadsansing - just let us know here what changes you'd like to make in advance of the next workshop, and when. We'll do with developer involvement for now, because this page is not yet a part of the CMS.

**Comment by KGorr** [comment]
Hey, sorry for the delay in adding to this. The G+ event page (and thus the video stream embed code), and new etherpad can be set up pretty quickly. 

My suggestion is to aim for getting these set up 1 week after last month's workshop so that we can archive the past episode quickly. When we start promoting the new episode, we don't want the old one to be on the home page. The event page may not have details that quickly, but we can just add generic content until then. @poh , thoughts on that since you'd be the one getting them set up? 

Also, easy naming convention for etherpads can be "curriculumworkshop[month]"...

**Comment by Pomax** [comment]
As a side-question, should this work be steering part of the CMS work we're doing, or does it need to land before we finish up the CMS MVP?

**Comment by hannahkane** [comment]
I'm actually not sure we need this ticket anymore. We have [this ticket](https://github.com/mozilla/teach.mozilla.org/issues/1758) to migrate this page to CMS eventually, and, in the meantime, @flukeout filed a PR to update the content of the page.

Closing unless someone objects.
