### ISSUE TITLE
Make three icons on /badges look less clickable

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1773]
The three icons (Explore, Earn, Share) at the top of the Badges page look like immediate actions the user should take (i.e. they look clickable), instead of a quick way for people to understand what Badges are about.

@kristinashu @sabrinang - do you agree, and if so, do you have any suggestions for what we might do to make this section seem less like a CTA and more like an intro to badges?

**Comment by hannahkane** [comment]
For reference: https://drive.google.com/a/mozillafoundation.org/file/d/0B2irLVDJivhLOEIzWkZiM3c5ZVE/view

**Comment by sabrinang** [comment]
They don’t look immediately actionable to me but I understand that it has a similar treatment to the bottom 3 CTAs by the footer and that could cause this confusion. Similar to how @kristinashu has treated the 3 science illustrations on their landing page, we can perhaps remove the titles that would make it look less clickable but I do like this concise copy that communicates the content though.

**Comment by Pomax** [comment]
remember to look at it as if it's on a screen, so you get the "fold" pretty much after the skills text - these are the only three image you see, so interpreting them as navigation elements becomes a lot more intuitive in that context

**Comment by kristinashu** [comment]
We should try to make this page more consistent with the rest of the site anyways. I recommend we try to align with to top part of https://teach.mozilla.org/tools and https://teach.mozilla.org/community
- use the same banner height (maybe use an image instead of the purple pattern)
- instead of the 3 icons and text we should use a large circle icon (place holder icon is in the comp below) and update the text to a short paragraph rather than the three separate points.

![mln-badges-comps-update 2x](https://cloud.githubusercontent.com/assets/1068783/14661826/b4b8605c-0665-11e6-934d-e828b333b0b2.jpg)

@sabrinang thoughts?

**Comment by sabrinang** [comment]
:+1: @kristinashu Yes, I like that idea of using a photo for the hero banner and using the large circle icon with intro paragraph as well to match the other sections.

Also, for the sign in button section we can try to make it look like the existing sections where there is a vertical line that leads to larger centered text and button with the divider beneath (instead of being in between two dividers)
![teach_example-button](https://cloud.githubusercontent.com/assets/2492510/14683390/5e7810be-06df-11e6-85ca-04a403c92a9d.jpg)

**Comment by kristinashu** [comment]
Thanks @sabrinang, good call. I'll work these updates, the circle icon and a background image

**Comment by kristinashu** [comment]
I've updated the comp with an image and circle icon (taken from TLM since it's no longer around).

@sabrinang two versions below, one with the vertical line and one with the two horizontal lines. What do you think? I know the vertical line is more on brand but I think it maybe looks slightly odd because the sign in copy is so short? But maybe it's ok.

![2x_landing not signed in copy 2](https://cloud.githubusercontent.com/assets/1068783/14754938/6dd578a2-0893-11e6-8458-ebe954dc0f07.jpg)

![2x_landing not signed in copy](https://cloud.githubusercontent.com/assets/1068783/14754937/6dd5474c-0893-11e6-9c76-7c14502cce47.jpg)

**Comment by kristinashu** [comment]
@Pomax here is the updated comp https://redpen.io/xz6664fcf5a9f4819f

Banner image and circle icon svg are here:
[updates.zip](https://github.com/mozilla/teach.mozilla.org/files/241468/updates.zip)

Are you good to implement this? Let me know if you need anything else or have any questions.

**Comment by Pomax** [comment]
This looks pretty good as a redpen, but implement on the page actually forces users to scroll to see badges, which feels like content they should be immediately confronted with.

![screenshot 269](https://cloud.githubusercontent.com/assets/177243/14998879/db125a98-113a-11e6-8acd-f04a5f8806c0.png)

**Comment by kristinashu** [comment]
This is how a lot of pages on the site are and I wouldn't worried about 'the fold'. Research shows the fold is less and less important and people will scroll down a page.

**Comment by Pomax** [comment]
can do.
