### ISSUE TITLE
Update skills in Web Lit Basics 1 module to match new Web Lit Map 2.0

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1791]
The six activities in the [Web Lit Basics 1 module](https://teach.mozilla.org/activities/web-lit-basics/) need to be updated to reflect the new skills/verbs in the Web Lit Map 2.0.

In the sidebar on these activities, we need to:
- [x] Change Web Literacy Competencies to Web Literacy **Skills**
- [x] Add 21st Century Skills

Reference this document to see what the updated skills are for each of the activities: 
https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#heading=h.hwiildxvzsx4

cc @chadsansing @anmechung

**Comment by hannahkane** [comment]
I suggest that we migrate these six activities to the new template (as in the Web Lit Basics II module).

Also suggest we move ALL Web Lit Basics (I and II) to mozilla.github.io, rather than attach to a specific staff person.

@chadsansing - what do you think of this? I can help with some of the grunt work.

**Comment by chadsansing** [comment]
@hannahkane, yes to the migration to mozilla.github.io.

If we can band-aid the Web Lit and 21st C skills for now, I'd be happy to help migrate the Web Lit Basics lessons to the new template after getting more leadership curriculum finished.

**Comment by hannahkane** [comment]
Alternative idea: what if we move all of this to Thimble projects, since we have the new lesson plan template in Thimble as well. That would make all of this content remixable. Is that desirable?

**Comment by anmechung** [comment]
+1 to chadsansing band-aid for now - can these edits be made by Wed? We're going to launch a blog and other communication on Wed, and it would be best if these edits could be made by then.

**Comment by chadsansing** [comment]
@hannahkane, seems like Thimble versions would be difficult to update, but the more access the better, generally. Probably needs a convo between now and when we update.

**Comment by hannahkane** [comment]
yes, also remembering that we have them as github pages for l10n reasons, too.

I'll work on updating these, as is, now. But we should have a conversation with @soapdog soon about how we might migrate to the new template, while respecting l10n work that's happened already.

**Comment by soapdog** [comment]
@hannahkane and @chadsansing,

The Web Lit I activities were placed on separate github repos to handle the L10N process through the usage of the github issue system. I think it is easier to move them to the new template by keeping them where they are and changing code instead of moving them to thimble. Thimble URLs are less memorable and have no version control, so I believe, thimble is awesome to prototype activities but their final form should be inside a repo.

I can migrate them to the new template, it just requires grafting some of the L10N code into the new layout. :smile_cat:

**Comment by hannahkane** [comment]
@soapdog - yep, that makes sense.

re: the original ask on this ticket—I filed [this PR](https://github.com/mozilla/mozilla-club-activity-kraken-the-code/pull/32) for Kraken the Code specifically. Can you take a look, and, if it's good, I can update the others as well. Not sure how to go about adding 21st Century Skills, though, since we don't have a mockup for that in the template.

**Comment by hannahkane** [comment]
ok, PRs filed for all six activities. waiting for @soapdog to review in case I messed anything up. :)

**Comment by soapdog** [comment]
@hannahkane started reviewing and merging them now

**Comment by soapdog** [comment]
@hannahkane all reviewd and merged! Awesome work, thanks so much! :+1: :+1: :+1: :smile_cat:

**Comment by hannahkane** [comment]
yay! thanks, @soapdog!

closing this ticket. Andre, I'll file another ticket for migrating to the new template.
