### ISSUE TITLE
Consider pairing tests with components

### ISSUE THREAD

**Issue by k88hudson** [mozilla/teach.mozilla.org#332]
Generally, I really like your automated tests for react components :dancer: 

I was thinking in order to ensure tests get written for new components, it might be a good idea to pair tests with components. So for example 

```
components/
--- apple/
        apple.jsx
        apple.test.jsx
--- orange/
        orange.jsx
        orange.test.jsx
```

The downside of this is that you'd  have a deeper folder structure, but I feel like it would be really useful especially if you want to actually convert the component to be a separate module.

What do you think @toolness @gvn?

**Comment by toolness** [comment]
Thanks!

Hmm that's a good question... Back in #233 @alicoding actually originally suggested having a separate directory for each component, so that we could store the `less` alongside the `jsx` like you do in [your `react-web-app`](https://github.com/k88hudson/react-web-app). But we ran into [problems](https://github.com/mozilla/teach.webmaker.org/pull/238#issuecomment-78269006) when trying to name every component `index.jsx`... However, you're not suggesting that part, which makes things easier!

The only other concern I have, though, is that there are distinctly different tests for the node environment and the browser environment. It might even be the case that we want to separately test certain components in the browser vs. node in the future (we don't do that right now, though--right now every JSX component is *only* tested in the browser).

Anyways, right now we *could* do that by having all the files immediately inside `test/` be run in the node environment, while everything under `test/browser/` is run in the browser. If I wanted to test the `apple` component *both* on the server and the browser, I could make a `test/apple.test.jsx` and a `test/browser/apple.test.jsx`... How would I do that with your suggested reorganization, though? Maybe `apple.test.browser.jsx` and `apple.test.node.jsx`?

**Comment by k88hudson** [comment]
Totally agree 100% with naming things `name/name.jsx` instead of `name/index.jsx`. In order to simplify the mocha `globs`, I think i would prefer either:

```
apple/
  apple.jsx
  apple.browser.test.jsx
  apple.node.test.jsx
  apple.manual.test.jsx
```

or 

```
apple/
  apple.jsx
  tests/
    apple.browser.test.jsx
    apple.node.test.jsx
    apple.manual.test.jsx
```

What do you think?

**Comment by k88hudson** [comment]
(You might not need individual manual tests, but you know, in the future or on some other project ^_^)

**Comment by gvn** [comment]
I prefer name over index too because it makes tabs in Sublime more clear. :+1:

**Comment by k88hudson** [comment]
also debugging/source maps!! holy crap is it annoying when everything is the same filename

**Comment by gvn** [comment]
I don't know if this is over-engineering, but you might want to consider a Yeoman generator for all this.

**Comment by toolness** [comment]
Nice!! I dig it!

I am unfamiliar with Yeoman, I will have to read up on it...

**Comment by hannahkane** [comment]
Is this ticket still needed, or can it be closed?
