### ISSUE TITLE
Implement the design for the accessible Clubs list

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#443]
Design was done in #245.

@iamjessklein - can you provide the assets?

**Comment by iamjessklein** [comment]
The only additional assets here are the map icons. @toolness - should I go ahead and purchase them?

**Comment by iamjessklein** [comment]
I would actually start to implement without the flags. I am having a difficult time finding a set that permits open source use. [This is the set](https://www.iconfinder.com/iconsets/flags-of-the-world-2) that I was going to get, however these restrictions in the TOS seem to be restricting the use:
![deh0c_e4mp](https://cloud.githubusercontent.com/assets/535012/6876818/97bbea38-d4a1-11e4-911a-e4960de80696.png)

However, it does say they permit usage in "On-line content" so I am going to try contacting them to see if it's permissible.

**Comment by toolness** [comment]
I can bust this up. Jess and I were talking about an approach that doesn't involve using the flags, where we could riff off the [LittleBits Chapters](http://littlebits.cc/community/chapters) design:

![2015-04-09_13-03-59](https://cloud.githubusercontent.com/assets/124687/7072272/f812d07e-deb8-11e4-9fe6-f800d084e624.jpg)

Basically, instead of the flags, and instead of the three-letter city codes on the LittleBits site, we could show a unique color combined with the [2 or 3-letter country code](http://www.worldatlas.com/aatlas/ctycodes.htm) for the country that the club is in.

**Comment by hannahkane** [comment]
woohoo! excited for the busting that's going to happen. :ghost:

**Comment by iamjessklein** [comment]
Really nice @toolness - this is what I was visualizing. How are these colors generated? It would be nice to build off of our core palette and then move into shades.
