### ISSUE TITLE
TEACHING ACTIVITIES: Activities should open in a new tab

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.mozilla.org#476]
Each learning activity should open in a new tab so that a user stays on the Teach site.

**Comment by hannahkane** [comment]
Do we have a standard best practice about this? I know it's a contentious issue in the UX world. I'm an anti-new tabs person. :) This post sums up my stance on The Great New Tab Debate: http://libux.co/links-should-open-in-the-same-window/

Will follow your lead, @iamjessklein, but just wanted to make sure we've considered the (user-centered!) no-new-tabs approach. :)

**Comment by jgmac1106** [comment]
Tabbed browsing is a friend of reading comprehension.

Thanks for sharing the link to the research. I look forward to digging into
it. Mainly because the results are in stark contrast of research with
novice web users.

In the work I am familiar with (verbal protocol analysis with urban youth)
tabbed browsing reduces the number of times readers get lost.

Navigational skills are a clear difference between skilled and novice
readers. So it might be a casual link but those who use tabs perform better
on measures of understanding.

I get the idea that allowing the user to control how links open is
considered gospel by many.

Yet the target audience of the curriculum may not even possess the skills
to change these settings or may work on machines with very tight
restrictions on changing settings.

**Comment by iamjessklein** [comment]
I put this up for the purpose of debate. I *think* that it is disruptive to the user in this case because the activity page is on Thimble, which is a related, but unlinked and differently branded Mozilla property. This is something that is definitely user testable before any changes are made.

**Comment by hannahkane** [comment]
I <3 the idea of including this as part of our user testing.

I find @jgmac1106's arguments about the audience convincing, but I don't feel I actually know enough about our target/actual audience yet to know if it applies here.

Another option is to offer a "open in new tab" option on the page and truly let the user decide.

**Comment by ScottDowne** [comment]
I'm a fan of new tabs, so much so that I never click links, I always right click > Open link in new tab

So my flow isn't disrupted and I don't lose links.

**Comment by hannahkane** [comment]
I also right click, but I like having the choice and don't like unexpected behavior.

@iamjessklein - I think this is your call. Also note, we should decide if our rule is we open every link in a new tab, all external links, only the links on the Teaching Activities/ClubsCurriculum pages, or no links.
