### ISSUE TITLE
Event resources page uses a similar png for an existing svg file

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.mozilla.org#627]
![logos](https://cloud.githubusercontent.com/assets/197334/7071949/8dea6a92-deb6-11e4-9cb7-27345f52f518.png)

I added both to that screen shot to compare. I labeled them and display them with the other logos to show contrast.

The svg doesn't match, so I was hesitant to use it, because it has a much different shade of green.

**Comment by hannahkane** [comment]
@sabrinang - can you please advise?

**Comment by ScottDowne** [comment]
Totally not a blocker to shipping.

**Comment by hannahkane** [comment]
k. :)

**Comment by mmmavis** [comment]
From the screencap comparison below, my guess is there was some sort of CSS opacity applied to the thumbnail section.  That's why it affected the `.png` but not `.svg`? 

Anyways, I'm closing this ticket as it's N/A now :grin: 


### Current

<img width="1018" alt="screen shot 2015-09-28 at 12 07 02 pm" src="https://cloud.githubusercontent.com/assets/2896608/10145703/8822c154-65d9-11e5-9404-243631df10fa.png">

### Screencap @ScottDowne took in April

![logos](https://cloud.githubusercontent.com/assets/197334/7071949/8dea6a92-deb6-11e4-9cb7-27345f52f518.png)
