### ISSUE TITLE
Convert more PNG-based photos into JPEGs

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.mozilla.org#790]
![image](https://cloud.githubusercontent.com/assets/25260/7283676/088394c8-e8ed-11e4-8290-052fae361393.png)

**Comment by toolness** [comment]
Hmm, it shouldn't be loading `app.bundle.js.map` outside of devtools though, right? If it is ... I am upset, because I want to encourage folks to pop open the hood of our site without having to clone our github repo and set it up on their local system.

**Comment by simonwex** [comment]
Correct, I should have chopped that from my screen grab. The 1 MB hero image (retina and non-retina) seems excessive, perhaps we should split this issue into "Optimize images" and "Only load correct version of hero image"

**Comment by toolness** [comment]
I was going to file a new issue for converting photographic PNGs into JPEGs, but I realized this issue is basically it.

In #946 we added a way to easily convert photographic, lossless PNGs into lossy JPEGs at build time, and did it for hero unit images only. We should go ahead and do the conversion for *all* our photographic PNGs, such as the `maurya-nyc@2x.png` listed at the top of this issue.

**Comment by mmmavis** [comment]
Moving this to Jan 15, 2016 heartbeat for further discussion

**Comment by Pomax** [comment]
this still seems an imminently good idea.

**Comment by Pomax** [comment]
having a look at the image footprints, things got slimmed down considerably already, so closing this.
