### ISSUE TITLE
Port Literacy page translations

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#947]
The Web Literacy page has been translated previously, so we need to port those translations to the new Teach design. 

 - [ ] Determine mechanism for doing this technically
 - [ ] Identify if any changes were made to the copy during the transition - i.e. is there a delta that needs to be translated in every language? (Update: yes, [see below](https://github.com/mozilla/teach.webmaker.org/issues/947#issuecomment-107556270))
 - [ ] Provide UX or browser locale detection to serve up the right translation to users

**Comment by toolness** [comment]
It seems like that third checkbox, "Provide UX or browser locale detection to serve up the right translation to users", should ultimately be global to the whole site, i.e. the weblit page shouldn't have a separate "choose your language" selector from the rest of the site. Er, unless it might be the case that the weblitmap is actually localized in more languages than the rest of the site, in which case we'll have to figure something out. I just added a note about this in #916.

**Comment by hannahkane** [comment]
Agreed that the ultimate solution should apply to the site globally. If we localize sections of the site in phases, we'll need an interim solution, though, right?

**Comment by toolness** [comment]
Um as a side note, this is how the current Web Literacy page on webmaker.org looks on Google:

![2015-06-01_7-21-18](https://cloud.githubusercontent.com/assets/124687/7911738/e2d4dec4-082e-11e5-8ca0-d6b5e27f5b05.jpg)

... so we should make sure our result never ever looks like that.

**Comment by toolness** [comment]
Ack.

Ok, I started working on a solution for this in #964, but then I noticed your second checkbox, "Identify if any changes were made to the copy during the transition "... And it looks like our [Transifex `weblitmap` resource](https://www.transifex.com/projects/p/webmaker/viewstrings/#en_US/web-literacy-map/23346361) is unfortunately for the [legacy version 1.1](https://github.com/mozilla/webliteracymap/tree/master/v1.1%20%28legacy%29) of the map, not the newer [version 1.5](http://literaci.es/web-literacy-map-v1-5) which was recently released on March 20.

Um, I also didn't notice that there's apparently a [web-literacy-client](https://github.com/mozilla/web-literacy-client) github project that might have obviated the need for me to start my PR at all... Oh well.

Anyways, the fact that we don't have *any* translations of v1.5 of the literacy map sort of puts us back at the drawing board, unfortunately--my assumption was that this was going to be relatively easy because the translations already exist, but this isn't the case, so there isn't really that much of a difference in localizing this content versus localizing the rest of the site--with the exception, I suppose, that this content is extremely unlikely to change any time soon, while the rest of the site's content is under a lot of flux.

Hmmmm.

**Comment by toolness** [comment]
> ... this content is extremely unlikely to change any time soon, while the rest of the site's content is under a lot of flux.

Er, as hannah just pointed out on our daily stand, the web literacy map strings might not be so stable either, as Mark's latest [blog post](https://commonspace.wordpress.com/2015/06/03/the-essence-of-web-literacy/) has the following photo in it:

<a href="https://commonspace.wordpress.com/2015/06/03/the-essence-of-web-literacy/"><img src="https://commonspace.files.wordpress.com/2015/06/fullsizerender1.jpg?w=402&h=177"></a>

<img src="http://media1.giphy.com/media/6OWIl75ibpuFO/giphy.gif" width="200">
